# Generated by Django 3.0.4 on 2020-04-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_belong_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invitated',
            field=models.BooleanField(blank=True, default=False, help_text='グループに招待中かどうか ', null=True, verbose_name='is invitated'),
        ),
    ]
