# Generated by Django 3.0.4 on 2020-05-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_auto_20200514_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menuapp.Category'),
        ),
    ]
