# Generated by Django 3.0.4 on 2020-04-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='title',
        ),
    ]
