# Generated by Django 3.0.4 on 2020-04-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0003_auto_20200426_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupapp.Group'),
        ),
    ]
