# Generated by Django 3.0.4 on 2020-04-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0001_initial'),
        ('groupapp', '0005_groupinvitatedmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='request_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestapp.RequestMenu'),
        ),
    ]
