# Generated by Django 3.0.4 on 2020-05-14 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('requests_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='リクエスト発行者')),
            ],
            options={
                'db_table': 'Requests',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='RequestMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.Menu')),
                ('requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestapp.Requests')),
            ],
            options={
                'db_table': 'RequestMenu',
            },
        ),
    ]
